import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";

export const metadata: Metadata = {
  title: "FitGenie - AI-Powered Fitness Coach",
  description: "Get personalized workout plans generated by AI, track your progress, and achieve your fitness goals with FitGenie - your intelligent fitness companion.",
  icons: {
    icon: [
      {
        url: '/fitgenie-icon.svg',
        type: 'image/svg+xml',
      },
      {
        url: '/favicon.ico',
        sizes: '32x32',
      }
    ],
    shortcut: '/fitgenie-icon.svg',
    apple: '/fitgenie-icon.svg',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <head>
        <link rel="icon" href="/fitgenie-icon.svg" type="image/svg+xml" />
        <link rel="icon" href="/favicon.ico" sizes="32x32" />
        <link rel="apple-touch-icon" href="/fitgenie-icon.svg" />
      </head>
      <body className="h-full font-sans antialiased transition-colors duration-300">
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
